Intrn 70 login repo
cmyui/osu-server-professing pull request #38
Opened 2023-05-04 16:42 UTC by James-Tepper

2023-05-04 23:48 UTC, cmyui commented on server/repositories/login_attempts.py
> +class Login_Attempt(TypedDict):
```suggestion
class LoginAttempt(TypedDict):
```

2023-05-04 23:48 UTC, cmyui commented on server/repositories/login_attempts.py
> +) -> Login_Attempt:
```suggestion
) -> LoginAttempt:
```

2023-05-04 23:48 UTC, cmyui commented on server/repositories/login_attempts.py
> +    return cast(Login_Attempt, login_attempt)
```suggestion
    return cast(LoginAttempt, login_attempt)
```

2023-05-04 23:48 UTC, cmyui commented on server/repositories/login_attempts.py
> +    return cast(Login_Attempt, login_attempt) if login_attempt is not None else None
```suggestion
    return cast(LoginAttempt, login_attempt) if login_attempt is not None else None
```

2023-05-04 23:48 UTC, cmyui commented on server/repositories/login_attempts.py
> +) -> list[Login_Attempt] | None:
```suggestion
) -> list[LoginAttempt] | None:
```

2023-05-04 23:48 UTC, cmyui commented on server/repositories/login_attempts.py
> +    return [cast(Login_Attempt, login_attempt) for attempt in login_attempt]
```suggestion
    return [cast(LoginAttempt, login_attempt) for attempt in login_attempt]
```

2023-05-04 23:48 UTC, cmyui commented on server/repositories/login_attempts.py
> +async def fetch_one(login_attempt_id: int) -> Login_Attempt | None:
```suggestion
async def fetch_one(login_attempt_id: int) -> LoginAttempt | None:
```

2023-05-04 23:50 UTC, cmyui commented on server/repositories/login_attempts.py
> +    login_attempt_id: int,
a given `login_attempt_id` will only ever return a single result, or none, so it doesn't make sense for a fetch_many. only fetch_one.

for this, the filter parameters we want are the `successful`, `ip_address`, and `user_agent`

2023-05-04 23:50 UTC, cmyui requested changes
requested minor changes - rest looks good!

2023-05-05 01:21 UTC, cmyui commented on server/repositories/login_attempts.py
> +) -> list[LoginAttempt] | None:
```suggestion
) -> list[LoginAttempt]:
```

2023-05-05 17:02 UTC, metal-face approved these changes

2023-05-06 16:28 UTC, cmyui commented on server/repositories/login_attempts.py
> +    return [cast(LoginAttempt, attempt) for attempt in login_attempt]
```suggestion
    login_attempts = await clients.database.fetch_all(query, values)
    return [cast(LoginAttempt, attempt) for attempt in login_attempts]
```

2023-05-06 16:29 UTC, cmyui approved these changes

2023-05-08 02:47 UTC, cmyui approved these changes

2023-05-08 02:47 UTC, merged